# -*- coding: utf-8 -*-
"""
data/company_showcase.py
'실시간 기업 탐색기' / '채용 대비 가이드' / '자소서 자동완성' 탭에서 쓰는
캐치(Catch) 스타일 기업 분석 카드 백업(모의) 데이터 20건.

※ 중요 안내
기업명은 학생들이 친숙하게 느낄 수 있도록 실제 대기업/공기업명을 일부
예시로 사용했지만(삼성전자, SK하이닉스, 현대자동차, 한국전력공사 등),
별점·복지·인재상·합격자 평균 스펙·선배 리뷰·면접질문 등 세부 내용은 모두
팀이 구성한 예시(모의) 콘텐츠이며 실제 사실이 아닙니다. 나머지 기업명은
전부 가상(fictional) 기업입니다. 화면에도 "예시 데이터" 라벨을 노출합니다.

각 항목 설명
------------
- ideal_talent: 캐치 스타일 "인재상 키워드" (자소서 생성 시 학생 강점과 매칭)
- avg_applicant_grade / avg_applicant_certs: "합격자 평균 스펙" 예시 (비교 서사용)
- required_skills: 코멘토 스타일 커리큘럼 생성에 쓰이는 직무 핵심 스킬 목록
"""

COMPANY_SHOWCASE = [
    # ---------------- 기계 ----------------
    {"id": "hanbit_precision", "name": "한빛정밀공업", "size_tag": "강소기업", "field_tag": "기계",
     "category": "기계", "description": "CNC 정밀가공 전문",
     "overall_rating": 4.4, "hire_dept": "정밀가공 생산1팀",
     "benefit_short": "자격증 수당 지급, 기숙사 지원, 명절 상여금 등",
     "ratings": {"연봉 및 상여 보상": 4.1, "복리후생 & 사내 문화": 4.3, "교대강도 & 근무 환경": 4.6},
     "pros": "소규모 조직 특성상 밀착 멘토링이 이뤄지는 편으로 소개됩니다.",
     "cons": "대기업 대비 복지 규모는 작지만 실무 성장 속도가 빠른 편으로 소개됩니다.",
     "required_certs": ["컴퓨터응용선반기능사", "컴퓨터응용밀링기능사"],
     "exam_keywords": "CNC 프로그래밍 기초, 도면 해독, 측정기 사용법",
     "interview_questions": ["CNC 선반과 밀링의 차이를 간단히 설명해보세요.",
                              "도면을 보고 가공 순서를 계획해본 경험이 있나요?",
                              "작은 조직에서 일할 때 중요한 태도는 무엇인가요?"],
     "ideal_talent": ["성실", "꼼꼼함", "책임감"],
     "avg_applicant_grade": 3.2, "avg_applicant_certs": 2,
     "required_skills": ["CNC 프로그래밍 기초", "도면 해독", "측정기(마이크로미터·버니어캘리퍼스) 사용법", "가공 공차 이해"]},

    {"id": "taebaek_heavy", "name": "태백중공업", "size_tag": "대기업", "field_tag": "기계",
     "category": "기계", "description": "중공업 생산기술 및 설비 제작",
     "overall_rating": 4.5, "hire_dept": "생산기술부",
     "benefit_short": "정년 보장, 사내 대학 학위 취득 지원, 기숙사 무상 제공 등",
     "ratings": {"연봉 및 상여 보상": 4.6, "복리후생 & 사내 문화": 4.4, "교대강도 & 근무 환경": 3.9},
     "pros": "안정적인 고용과 체계적인 신입 교육 프로그램이 강점으로 소개됩니다.",
     "cons": "대형 설비 특성상 안전수칙 준수에 대한 부담이 있는 편으로 소개됩니다.",
     "required_certs": ["컴퓨터응용선반기능사", "일반기계기사"],
     "exam_keywords": "중공업 생산공정, 용접 기초, 설비 안전관리",
     "interview_questions": ["대형 설비 작업 시 가장 중요한 안전수칙은 무엇인가요?",
                              "체력적으로 힘든 업무를 견뎌낸 경험이 있나요?",
                              "선배와의 협업에서 갈등을 해결한 경험을 말해보세요."],
     "ideal_talent": ["안전의식", "협력", "끈기"],
     "avg_applicant_grade": 2.8, "avg_applicant_certs": 3,
     "required_skills": ["도면 해독", "용접 기초 이론", "설비 안전관리 규정", "품질검사 기초"]},

    {"id": "shinsung_precision", "name": "신성정공", "size_tag": "중견기업", "field_tag": "기계",
     "category": "기계", "description": "정밀가공 라인 운영",
     "overall_rating": 4.3, "hire_dept": "정밀가공 생산기술부",
     "benefit_short": "자격증 취득 축하금, 통근버스 운영, 자기계발비 지원 등",
     "ratings": {"연봉 및 상여 보상": 4.2, "복리후생 & 사내 문화": 4.1, "교대강도 & 근무 환경": 4.3},
     "pros": "자격증 취득을 적극 장려하는 사내 문화가 강점으로 소개됩니다.",
     "cons": "정밀가공 특성상 세밀한 집중력이 요구되는 편으로 소개됩니다.",
     "required_certs": ["컴퓨터응용밀링기능사", "생산자동화산업기사"],
     "exam_keywords": "정밀측정, CAD 도면 해석, 생산자동화 기초",
     "interview_questions": ["정밀가공에서 0.01mm 오차가 왜 중요한가요?",
                              "반복 작업에서 집중력을 유지하는 자신만의 방법은?",
                              "새로운 장비를 빠르게 익힌 경험이 있나요?"],
     "ideal_talent": ["집중력", "성실", "학습의지"],
     "avg_applicant_grade": 2.6, "avg_applicant_certs": 2,
     "required_skills": ["정밀측정 기법", "CAD 도면 해석", "생산자동화 기초", "품질관리 QC 7종 도구"]},

    {"id": "hyundai_motor", "name": "현대자동차", "size_tag": "대기업", "field_tag": "기계",
     "category": "기계", "description": "완성차 제조 및 조립",
     "overall_rating": 4.7, "hire_dept": "완성차 생산기술부",
     "benefit_short": "신차 구매 지원, 정년 보장, 사내 복지몰 운영 등",
     "ratings": {"연봉 및 상여 보상": 4.8, "복리후생 & 사내 문화": 4.6, "교대강도 & 근무 환경": 4.1},
     "pros": "장기 근속 혜택과 체계적인 직무교육이 강점으로 소개됩니다.",
     "cons": "라인 생산 특성상 표준작업 시간 준수 부담이 있는 편으로 소개됩니다.",
     "required_certs": ["생산자동화기능사", "컴퓨터응용밀링기능사"],
     "exam_keywords": "자동차 생산공정, 산업용 로봇 기초, 설비 안전관리",
     "interview_questions": ["컨베이어 라인에서 불량을 발견했을 때 대응 순서는?",
                              "산업용 로봇과 협업 시 가장 중요한 안전수칙은?",
                              "팀 프로젝트에서 협업이 어려웠던 경험을 소개해주세요."],
     "ideal_talent": ["도전", "협력", "안전의식"],
     "avg_applicant_grade": 2.4, "avg_applicant_certs": 3,
     "required_skills": ["자동차 생산공정 이해", "산업용 로봇 기초", "표준작업 절차(SOP)", "품질 이상감지"]},

    # ---------------- 전자/전기 ----------------
    {"id": "samsung_ds", "name": "삼성전자 DS부문", "size_tag": "대기업", "field_tag": "전자/전기",
     "category": "전자/전기", "description": "반도체 제조 및 설비",
     "overall_rating": 4.8, "hire_dept": "반도체 설비기술부",
     "benefit_short": "사내 대학 학위 지원, 사내식당 무료 제공 등",
     "ratings": {"연봉 및 상여 보상": 5.0, "복리후생 & 사내 문화": 4.5, "교대강도 & 근무 환경": 4.0},
     "pros": "성과급과 사내 학위 취득 지원 제도가 강점으로 소개됩니다.",
     "cons": "4조 3교대 순환 근무로 체력 부담이 있을 수 있는 편으로 소개됩니다.",
     "required_certs": ["전기기능사", "전자기기기능사"],
     "exam_keywords": "반도체 8대 공정 원리, 설비 회로 분석, 시퀀스 제어",
     "interview_questions": ["설비가 갑자기 멈췄을 때 PLC 회로 관점에서 먼저 체크할 절차는?",
                              "교대 근무의 체력적 한계를 이겨낼 각오가 되었나요?",
                              "복잡한 배선 트러블을 극복한 경험이 있나요?"],
     "ideal_talent": ["창의", "몰입", "정직"],
     "avg_applicant_grade": 1.9, "avg_applicant_certs": 3,
     "required_skills": ["반도체 8대 공정 개요", "설비 회로 분석", "시퀀스 제어(PLC) 기초", "클린룸 작업 수칙"]},

    {"id": "sk_hynix", "name": "SK하이닉스", "size_tag": "대기업", "field_tag": "전자/전기",
     "category": "전자/전기", "description": "메모리 반도체 생산",
     "overall_rating": 4.7, "hire_dept": "반도체 양산기술부",
     "benefit_short": "가족 의료비 지원, 기숙사 무상 지원, 자녀 학자금 지원 등",
     "ratings": {"연봉 및 상여 보상": 4.8, "복리후생 & 사내 문화": 4.6, "교대강도 & 근무 환경": 4.0},
     "pros": "가족 복지 항목이 폭넓은 편으로 소개됩니다.",
     "cons": "생산라인 특성상 초기 적응 기간이 필요한 편으로 소개됩니다.",
     "required_certs": ["설비보전기능사", "전기기능사"],
     "exam_keywords": "메모리 소자 공정, 설비보전 기초, 품질관리 QC 기법",
     "interview_questions": ["설비 이상 발생 시 원인 진단 절차를 설명해보세요.",
                              "교대 근무에서 인수인계가 중요한 이유는?",
                              "품질 불량을 발견하고 개선한 경험이 있나요?"],
     "ideal_talent": ["패기", "실행력", "협업"],
     "avg_applicant_grade": 2.0, "avg_applicant_certs": 3,
     "required_skills": ["메모리 소자 공정 개요", "설비보전 기초", "품질관리 QC 기법", "5S 현장관리"]},

    {"id": "korea_power", "name": "코리아파워시스템", "size_tag": "중견기업", "field_tag": "전자/전기",
     "category": "전자/전기", "description": "전기설비 유지보수",
     "overall_rating": 4.3, "hire_dept": "전기설비 유지보수팀",
     "benefit_short": "자격증 수당, 통근버스, 명절 상여금 등",
     "ratings": {"연봉 및 상여 보상": 4.1, "복리후생 & 사내 문화": 4.2, "교대강도 & 근무 환경": 4.4},
     "pros": "자격증 취득 시 즉시 수당이 반영되는 편으로 소개됩니다.",
     "cons": "현장 출장이 잦은 편으로 소개됩니다.",
     "required_certs": ["전기기능사", "전기산업기사"],
     "exam_keywords": "전기설비 점검, 배전반 구조, 전기안전 기준",
     "interview_questions": ["전기설비 점검 시 반드시 지켜야 할 안전수칙은?",
                              "현장 출장이 잦은 근무에 대해 어떻게 생각하나요?",
                              "전기기능사 실기 중 가장 어려웠던 과정은?"],
     "ideal_talent": ["책임감", "안전의식", "꼼꼼함"],
     "avg_applicant_grade": 2.9, "avg_applicant_certs": 2,
     "required_skills": ["전기설비 점검 절차", "배전반 구조 이해", "전기안전 기준(KEC)", "측정기기 사용법"]},

    {"id": "kepco", "name": "한국전력공사", "size_tag": "공기업", "field_tag": "전자/전기",
     "category": "전자/전기", "description": "전력 수송 및 배전 설비",
     "overall_rating": 4.9, "hire_dept": "송배전 제어실",
     "benefit_short": "전용 사택 무상 제공, 저리 이주 기금, 학자금 전액 지원 등",
     "ratings": {"연봉 및 상여 보상": 4.7, "복리후생 & 사내 문화": 4.9, "교대강도 & 근무 환경": 4.6},
     "pros": "공기업 특유의 고용 안정성과 지역 이주 지원이 강점으로 소개됩니다.",
     "cons": "전국 지사 순환 근무 가능성이 있는 편으로 소개됩니다.",
     "required_certs": ["전기기능사", "전기산업기사"],
     "exam_keywords": "배전설비 운영, 전기 안전관리, 송배전 계통 기초",
     "interview_questions": ["정전 발생 시 초기 대응 절차를 설명해보세요.",
                              "전국 지사 순환 근무에 대해 어떻게 생각하나요?",
                              "전기기능사 실기를 준비하며 어려웠던 점은?"],
     "ideal_talent": ["공공의식", "안전의식", "성실"],
     "avg_applicant_grade": 1.8, "avg_applicant_certs": 3,
     "required_skills": ["배전설비 운영 개요", "전기 안전관리", "송배전 계통 기초", "공기업 NCS 직무기초"]},

    # ---------------- IT/정보통신 ----------------
    {"id": "nextwave_soft", "name": "넥스트웨이브소프트", "size_tag": "강소기업", "field_tag": "IT/정보통신",
     "category": "IT/정보통신", "description": "백엔드 시스템 개발",
     "overall_rating": 4.5, "hire_dept": "백엔드 개발팀",
     "benefit_short": "자기계발비 지원, 자율 출퇴근, 신입 멘토링 프로그램 등",
     "ratings": {"연봉 및 상여 보상": 4.0, "복리후생 & 사내 문화": 4.7, "교대강도 & 근무 환경": 4.8},
     "pros": "자율 출퇴근과 성장 중심 문화가 강점으로 소개됩니다.",
     "cons": "대기업 대비 복지 규모는 작은 편으로 소개됩니다.",
     "required_certs": ["정보처리기능사", "네트워크관리사2급"],
     "exam_keywords": "자료구조 기초, 네트워크 기본개념, SQL 기초 문법",
     "interview_questions": ["정보처리기능사에서 배운 개념 중 실무에 쓰고 싶은 것은?",
                              "혼자 공부해서 문제를 해결한 경험을 소개해주세요.",
                              "Git 등 협업 도구를 사용해본 경험이 있나요?"],
     "ideal_talent": ["자기주도성", "성장지향", "협업"],
     "avg_applicant_grade": 2.5, "avg_applicant_certs": 2,
     "required_skills": ["자료구조/알고리즘 기초", "SQL 기초 문법", "Git 협업 기초", "REST API 개념"]},

    {"id": "cloudbase_korea", "name": "클라우드베이스코리아", "size_tag": "강소기업", "field_tag": "IT/정보통신",
     "category": "IT/정보통신", "description": "클라우드 인프라 운영",
     "overall_rating": 4.4, "hire_dept": "인프라 운영팀",
     "benefit_short": "장비 지원, 유연근무, 자격증 취득 비용 지원 등",
     "ratings": {"연봉 및 상여 보상": 4.2, "복리후생 & 사내 문화": 4.5, "교대강도 & 근무 환경": 4.3},
     "pros": "최신 기술 스택을 빠르게 접할 수 있는 편으로 소개됩니다.",
     "cons": "소규모 조직이라 1인당 담당 업무 범위가 넓은 편으로 소개됩니다.",
     "required_certs": ["리눅스마스터2급", "네트워크관리사2급"],
     "exam_keywords": "리눅스 기본 명령어, 네트워크 기초, 클라우드 개념",
     "interview_questions": ["리눅스 서버에서 자주 쓰는 명령어를 소개해보세요.",
                              "네트워크 장애를 진단해본 경험이 있나요?",
                              "새로운 기술을 스스로 학습한 경험을 말해보세요."],
     "ideal_talent": ["학습의지", "문제해결", "책임감"],
     "avg_applicant_grade": 2.3, "avg_applicant_certs": 2,
     "required_skills": ["리눅스 기본 명령어", "네트워크 기초(OSI 7계층)", "클라우드 개념(가상화)", "쉘 스크립트 기초"]},

    {"id": "hanbit_datacenter", "name": "한빛데이터센터", "size_tag": "강소기업", "field_tag": "IT/정보통신",
     "category": "IT/정보통신", "description": "데이터센터 운영 인프라",
     "overall_rating": 4.1, "hire_dept": "인프라 운영팀",
     "benefit_short": "야간수당 지급, 통근버스, 자격증 수당 등",
     "ratings": {"연봉 및 상여 보상": 3.9, "복리후생 & 사내 문화": 4.0, "교대강도 & 근무 환경": 3.8},
     "pros": "인프라 운영 실무를 폭넓게 경험할 수 있는 편으로 소개됩니다.",
     "cons": "야간 교대 근무가 포함되는 편으로 소개됩니다.",
     "required_certs": ["정보처리기능사", "리눅스마스터2급"],
     "exam_keywords": "서버 기초, 네트워크 모니터링, 장애 대응 절차",
     "interview_questions": ["서버 장애 발생 시 대응 순서를 설명해보세요.",
                              "야간 근무에 대한 각오가 되어 있나요?",
                              "모니터링 도구를 사용해본 경험이 있나요?"],
     "ideal_talent": ["침착함", "책임감", "꼼꼼함"],
     "avg_applicant_grade": 2.9, "avg_applicant_certs": 2,
     "required_skills": ["서버 기초 운영", "네트워크 모니터링", "장애 대응 절차", "리눅스 기본 명령어"]},

    # ---------------- 바이오/화학 ----------------
    {"id": "hanwha_solutions", "name": "한화솔루션", "size_tag": "중견기업", "field_tag": "바이오/화학",
     "category": "바이오/화학", "description": "태양광 및 화학 소재",
     "overall_rating": 4.6, "hire_dept": "화학소재 가공 공정제어실",
     "benefit_short": "임직원 정착 저리 주택 대출, 사내 세 끼 무료 식당 등",
     "ratings": {"연봉 및 상여 보상": 4.4, "복리후생 & 사내 문화": 4.6, "교대강도 & 근무 환경": 4.5},
     "pros": "정착 지원 대출, 무료 식당 등 생활 밀착형 복지가 강점으로 소개됩니다.",
     "cons": "화학 공정 특성상 엄격한 절차 준수가 요구되는 편으로 소개됩니다.",
     "required_certs": ["화학분석기능사", "위험물산업기사"],
     "exam_keywords": "화학공정 안전관리, 위험물 취급기준, 태양광 소재 기초",
     "interview_questions": ["화학물질 취급 시 지켜야 할 안전수칙 3가지는?",
                              "위험물산업기사를 준비하며 현장에 적용하고 싶은 내용은?",
                              "환경안전 관련 교내 활동 경험이 있나요?"],
     "ideal_talent": ["안전제일", "정직", "책임감"],
     "avg_applicant_grade": 2.4, "avg_applicant_certs": 2,
     "required_skills": ["화학공정 안전관리", "위험물 취급기준(MSDS)", "태양광 소재 기초", "공정계측 기초"]},

    {"id": "cosmax", "name": "코스맥스 (COSMAX)", "size_tag": "중견기업", "field_tag": "바이오/화학",
     "category": "바이오/화학", "description": "글로벌 화장품 연구제조",
     "overall_rating": 4.3, "hire_dept": "생산 가공 공정 보전팀",
     "benefit_short": "화장품 임직원 특가, 자녀 학자금 지원, 가족 건강검진 등",
     "ratings": {"연봉 및 상여 보상": 4.0, "복리후생 & 사내 문화": 4.5, "교대강도 & 근무 환경": 4.2},
     "pros": "화장품 특가 구매 등 가족 복지 항목이 다양한 편으로 소개됩니다.",
     "cons": "품질관리 기준이 까다로워 꼼꼼함이 요구되는 편으로 소개됩니다.",
     "required_certs": ["화학분석기능사"],
     "exam_keywords": "화장품 제조공정, 품질관리 기초, 원료 분석",
     "interview_questions": ["품질 기준을 벗어난 제품을 발견하면 어떻게 처리하겠습니까?",
                              "화학분석기능사 실습 중 가장 자신 있는 내용은?",
                              "꼼꼼함이 필요한 작업을 끝까지 완수한 경험이 있나요?"],
     "ideal_talent": ["꼼꼼함", "정직", "협업"],
     "avg_applicant_grade": 2.7, "avg_applicant_certs": 1,
     "required_skills": ["화장품 제조공정 개요", "품질관리 기초(QC)", "원료 분석 기초", "GMP 기본개념"]},

    {"id": "daehan_pharma", "name": "대한제약바이오", "size_tag": "대기업", "field_tag": "바이오/화학",
     "category": "바이오/화학", "description": "제약 생산 및 품질보증",
     "overall_rating": 4.5, "hire_dept": "생산1팀 품질보증실",
     "benefit_short": "정년 보장, 사내 어린이집, 건강검진 지원 등",
     "ratings": {"연봉 및 상여 보상": 4.5, "복리후생 & 사내 문화": 4.4, "교대강도 & 근무 환경": 4.3},
     "pros": "제약 산업 특유의 안정성과 체계적인 품질관리 교육이 강점으로 소개됩니다.",
     "cons": "GMP 규정 준수를 위한 문서작업이 많은 편으로 소개됩니다.",
     "required_certs": ["화학분석기능사", "식품기사"],
     "exam_keywords": "제약 GMP 기초, 품질보증 절차, 무균 작업 기초",
     "interview_questions": ["GMP 규정을 준수하는 것이 왜 중요하다고 생각하나요?",
                              "반복적인 문서 작업을 꾸준히 해낼 자신이 있나요?",
                              "정확성이 요구되는 작업에서의 경험을 말해주세요."],
     "ideal_talent": ["정직", "꼼꼼함", "준법정신"],
     "avg_applicant_grade": 2.1, "avg_applicant_certs": 2,
     "required_skills": ["제약 GMP 기초", "품질보증(QA) 절차", "무균 작업 기초", "문서관리 기초"]},

    # ---------------- 농생명 ----------------
    {"id": "cheongjeong_farm", "name": "청정팜 스마트팜", "size_tag": "중견기업", "field_tag": "농생명",
     "category": "농생명", "description": "스마트팜 재배 및 운영",
     "overall_rating": 4.2, "hire_dept": "스마트팜 운영팀",
     "benefit_short": "농기계 자격증 수당, 기숙사 지원, 명절 상여금 등",
     "ratings": {"연봉 및 상여 보상": 3.9, "복리후생 & 사내 문화": 4.1, "교대강도 & 근무 환경": 4.3},
     "pros": "ICT 융합 스마트팜 실무를 경험할 수 있는 편으로 소개됩니다.",
     "cons": "계절에 따라 업무 강도 차이가 있는 편으로 소개됩니다.",
     "required_certs": ["시설원예기능사", "종자기능사"],
     "exam_keywords": "스마트팜 센서 시스템, 작물 생육 관리, 환경제어 기초",
     "interview_questions": ["스마트팜 센서 데이터를 활용해본 경험이 있나요?",
                              "계절별 업무 강도 변화에 대해 어떻게 대비하겠습니까?",
                              "작물 재배 중 문제를 해결한 경험이 있나요?"],
     "ideal_talent": ["관찰력", "성실", "적응력"],
     "avg_applicant_grade": 3.0, "avg_applicant_certs": 1,
     "required_skills": ["스마트팜 센서/환경제어 기초", "작물 생육 관리", "농업 ICT 기초", "데이터 기록·분석 습관"]},

    {"id": "sillip_bakery", "name": "삼립베이커리랩", "size_tag": "중견기업", "field_tag": "농생명",
     "category": "농생명", "description": "제과·제빵 생산기술",
     "overall_rating": 4.3, "hire_dept": "생산기술팀",
     "benefit_short": "제품 할인 구매, 명절 상여금, 자격증 수당 등",
     "ratings": {"연봉 및 상여 보상": 4.0, "복리후생 & 사내 문화": 4.3, "교대강도 & 근무 환경": 4.0},
     "pros": "제과·제빵 실무 역량을 빠르게 쌓을 수 있는 편으로 소개됩니다.",
     "cons": "새벽 근무가 포함될 수 있는 편으로 소개됩니다.",
     "required_certs": ["제과기능사", "제빵기능사"],
     "exam_keywords": "베이커리 위생관리, 발효 공정 기초, 대량생산 공정",
     "interview_questions": ["새벽 근무 가능 여부와 체력 관리 방법은?",
                              "위생관리 수칙 중 가장 중요하다고 생각하는 것은?",
                              "제과·제빵 실습 중 실패를 극복한 경험이 있나요?"],
     "ideal_talent": ["위생의식", "성실", "체력"],
     "avg_applicant_grade": 3.1, "avg_applicant_certs": 2,
     "required_skills": ["베이커리 위생관리(HACCP)", "발효 공정 기초", "대량생산 공정 이해", "원가/배합비 계산"]},

    # ---------------- 해양 ----------------
    {"id": "donghae_shipbuilding", "name": "동해조선기술", "size_tag": "대기업", "field_tag": "해양",
     "category": "해양", "description": "선박 의장 생산기술",
     "overall_rating": 4.4, "hire_dept": "선박 의장부",
     "benefit_short": "정년 보장, 사택 지원, 자격증 취득 지원금 등",
     "ratings": {"연봉 및 상여 보상": 4.5, "복리후생 & 사내 문화": 4.2, "교대강도 & 근무 환경": 3.8},
     "pros": "대형 조선 프로젝트 참여 경험을 쌓을 수 있는 편으로 소개됩니다.",
     "cons": "고소·밀폐 작업 등 위험 요소가 있는 편으로 소개됩니다.",
     "required_certs": ["조선기능사"],
     "exam_keywords": "선박 의장 기초, 용접 안전, 밀폐공간 작업 수칙",
     "interview_questions": ["밀폐공간 작업 시 반드시 지켜야 할 안전수칙은?",
                              "고소 작업에 대한 두려움을 어떻게 극복하겠습니까?",
                              "팀 단위 협업에서 본인의 역할을 설명해보세요."],
     "ideal_talent": ["안전의식", "협력", "책임감"],
     "avg_applicant_grade": 2.7, "avg_applicant_certs": 1,
     "required_skills": ["선박 의장 기초", "용접 안전수칙", "밀폐공간 작업 절차", "도면 해독"]},

    {"id": "hanju_shipbuilding", "name": "한주조선산업", "size_tag": "중견기업", "field_tag": "해양",
     "category": "해양", "description": "조선 생산관리",
     "overall_rating": 4.1, "hire_dept": "생산관리팀",
     "benefit_short": "통근버스, 명절 상여금, 자격증 수당 등",
     "ratings": {"연봉 및 상여 보상": 4.0, "복리후생 & 사내 문화": 4.0, "교대강도 & 근무 환경": 4.0},
     "pros": "생산관리 실무 전반을 경험할 수 있는 편으로 소개됩니다.",
     "cons": "수주 상황에 따라 업무량 변동이 있는 편으로 소개됩니다.",
     "required_certs": ["조선산업기사", "조선기능사"],
     "exam_keywords": "생산관리 기초, 공정관리, 자재관리",
     "interview_questions": ["생산 일정이 지연될 때 어떻게 대응하겠습니까?",
                              "자재관리 경험이나 관련 학습 내용이 있나요?",
                              "업무량 변동에 유연하게 대처할 수 있나요?"],
     "ideal_talent": ["유연성", "책임감", "협업"],
     "avg_applicant_grade": 3.0, "avg_applicant_certs": 1,
     "required_skills": ["생산관리 기초", "공정관리(간트차트 등)", "자재관리 기초", "도면 해독"]},
    {"id": "daesung_mecha", "name": "대성메카트로닉스", "size_tag": "강소기업", "field_tag": "기계",
     "category": "기계", "description": "생산자동화 설비 엔지니어링",
     "overall_rating": 4.2, "hire_dept": "자동화 설비기술팀",
     "benefit_short": "자격증 수당, 기숙사 지원, 명절 상여금 등",
     "ratings": {"연봉 및 상여 보상": 3.9, "복리후생 & 사내 문화": 4.1, "교대강도 & 근무 환경": 4.3},
     "pros": "PLC 자동화 설비 실무를 폭넓게 경험할 수 있는 편으로 소개됩니다.",
     "cons": "소규모 조직이라 1인당 담당 설비 범위가 넓은 편으로 소개됩니다.",
     "required_certs": ["생산자동화기능사", "전기기능사"],
     "exam_keywords": "PLC 시퀀스 제어, 자동화 설비 점검, 센서/액추에이터 기초",
     "interview_questions": ["PLC 프로그램을 직접 수정해본 경험이 있나요?",
                              "설비 점검 중 이상을 발견했을 때 보고 절차는?",
                              "여러 설비를 동시에 담당하는 상황에 대해 어떻게 생각하나요?"],
     "ideal_talent": ["문제해결", "책임감", "학습의지"],
     "avg_applicant_grade": 3.0, "avg_applicant_certs": 2,
     "required_skills": ["PLC 시퀀스 제어", "센서/액추에이터 기초", "자동화 설비 점검", "도면 해독"]},

    # ---------------- 건축/토목 ----------------
    {"id": "woosung_construction", "name": "우성건설", "size_tag": "중견기업", "field_tag": "건축/토목",
     "category": "건축/토목", "description": "건축시공 현장기술직",
     "overall_rating": 4.2, "hire_dept": "건축시공팀",
     "benefit_short": "현장수당 지급, 자격증 취득 지원금, 명절 상여금 등",
     "ratings": {"연봉 및 상여 보상": 4.0, "복리후생 & 사내 문화": 4.0, "교대강도 & 근무 환경": 3.9},
     "pros": "다양한 현장 경험을 통해 시공 실무를 빠르게 익힐 수 있는 편으로 소개됩니다.",
     "cons": "현장 특성상 외부 작업과 이동이 잦은 편으로 소개됩니다.",
     "required_certs": ["건축산업기사", "건축목공기능사"],
     "exam_keywords": "건축시공 기초, 도면 해독, 현장 안전관리",
     "interview_questions": ["건축 현장에서 가장 중요한 안전수칙은 무엇이라고 생각하나요?",
                              "외부 작업이 많은 근무 환경에 대해 어떻게 생각하나요?",
                              "도면을 보고 시공 순서를 계획해본 경험이 있나요?"],
     "ideal_talent": ["안전의식", "협력", "성실"],
     "avg_applicant_grade": 3.1, "avg_applicant_certs": 1,
     "required_skills": ["건축시공 기초", "도면 해독", "현장 안전관리", "공정표 이해"]},
]

COMPANY_CATEGORIES = ["전체", "기계", "전자/전기", "IT/정보통신", "바이오/화학", "농생명", "해양", "건축/토목"]
COMPANY_SIZE_TAGS = ["전체", "대기업", "중견기업", "공기업", "강소기업"]

COMPANY_BY_ID = {c["id"]: c for c in COMPANY_SHOWCASE}

assert len(COMPANY_SHOWCASE) == 20, "백업 기업 데이터는 요구사항에 따라 20건이어야 합니다."
